/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesOutrightPropertySaleRouteImport } from './routes/services/outright-property-sale'
import { Route as ServicesJointVentureRouteImport } from './routes/services/joint-venture'
import { Route as ServicesJointDevelopmentRouteImport } from './routes/services/joint-development'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal/disclaimer'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOutrightPropertySaleRoute =
  ServicesOutrightPropertySaleRouteImport.update({
    id: '/services/outright-property-sale',
    path: '/services/outright-property-sale',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesJointVentureRoute = ServicesJointVentureRouteImport.update({
  id: '/services/joint-venture',
  path: '/services/joint-venture',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesJointDevelopmentRoute =
  ServicesJointDevelopmentRouteImport.update({
    id: '/services/joint-development',
    path: '/services/joint-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/joint-development': typeof ServicesJointDevelopmentRoute
  '/services/joint-venture': typeof ServicesJointVentureRoute
  '/services/outright-property-sale': typeof ServicesOutrightPropertySaleRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/joint-development': typeof ServicesJointDevelopmentRoute
  '/services/joint-venture': typeof ServicesJointVentureRoute
  '/services/outright-property-sale': typeof ServicesOutrightPropertySaleRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/joint-development': typeof ServicesJointDevelopmentRoute
  '/services/joint-venture': typeof ServicesJointVentureRoute
  '/services/outright-property-sale': typeof ServicesOutrightPropertySaleRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/joint-development'
    | '/services/joint-venture'
    | '/services/outright-property-sale'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/joint-development'
    | '/services/joint-venture'
    | '/services/outright-property-sale'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/joint-development'
    | '/services/joint-venture'
    | '/services/outright-property-sale'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ServicesJointDevelopmentRoute: typeof ServicesJointDevelopmentRoute
  ServicesJointVentureRoute: typeof ServicesJointVentureRoute
  ServicesOutrightPropertySaleRoute: typeof ServicesOutrightPropertySaleRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/outright-property-sale': {
      id: '/services/outright-property-sale'
      path: '/services/outright-property-sale'
      fullPath: '/services/outright-property-sale'
      preLoaderRoute: typeof ServicesOutrightPropertySaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/joint-venture': {
      id: '/services/joint-venture'
      path: '/services/joint-venture'
      fullPath: '/services/joint-venture'
      preLoaderRoute: typeof ServicesJointVentureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/joint-development': {
      id: '/services/joint-development'
      path: '/services/joint-development'
      fullPath: '/services/joint-development'
      preLoaderRoute: typeof ServicesJointDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ServicesJointDevelopmentRoute: ServicesJointDevelopmentRoute,
  ServicesJointVentureRoute: ServicesJointVentureRoute,
  ServicesOutrightPropertySaleRoute: ServicesOutrightPropertySaleRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
